import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { of, throwError } from 'rxjs';
import { CallResponse } from '../../../core/api/models/call.models';
import { AgentsApiService } from '../../../core/api/services/agents-api.service';
import { CallsApiService } from '../../../core/api/services/calls-api.service';
import { AuthStore } from '../../../core/auth/auth.store';
import { AgentWorkspace } from './agent-workspace';

describe('AgentWorkspace',()=>{
 const current=vi.fn(),accept=vi.fn(),complete=vi.fn(),agentCurrent=vi.fn(),updateStatus=vi.fn();let fixture:ComponentFixture<AgentWorkspace>;
 const assigned:CallResponse={id:'c1',callReferenceNumber:'CALL-1',direction:'Inbound',status:'Assigned',customer:null,callQueueId:'q1',callQueueName:'Support',assignedAgentId:'a1',assignedAgentName:'Agent One',createdAtUtc:'2026-07-01T00:00:00Z',assignedAtUtc:'2026-07-01T00:00:01Z',acceptedAtUtc:null,completedAtUtc:null,outcome:null,notes:null,crmSyncStatus:'Pending',durationSeconds:null};
 beforeEach(async()=>{vi.clearAllMocks();current.mockReturnValue(of(assigned));agentCurrent.mockReturnValue(of({id:'a1',displayName:'Agent One',status:'Available',lastAvailableAtUtc:null,callQueueNames:['Support']}));await TestBed.configureTestingModule({imports:[AgentWorkspace],providers:[provideNoopAnimations(),{provide:CallsApiService,useValue:{current,accept,complete}},{provide:AgentsApiService,useValue:{current:agentCurrent,updateStatus}},{provide:AuthStore,useValue:{isAuthenticated:()=>true}}]}).compileComponents();fixture=TestBed.createComponent(AgentWorkspace);fixture.detectChanges();await new Promise(r=>setTimeout(r,10));fixture.detectChanges()});
 it('offers manual statuses without Busy and blocks controls during calls',()=>{const text=(fixture.nativeElement as HTMLElement).textContent;expect(text).toContain('Available');expect(text).toContain('On break');expect(text).toContain('Offline');expect(Array.from(fixture.nativeElement.querySelectorAll('.status-actions button') as NodeListOf<HTMLButtonElement>).every(b=>b.disabled)).toBe(true);expect(updateStatus).not.toHaveBeenCalled()});
 it('accepts once, shows elapsed active time, validates outcome/notes, and completes once',()=>{const active={...assigned,status:'Active' as const,acceptedAtUtc:new Date(Date.now()-65000).toISOString()};accept.mockReturnValue(of(active));(fixture.nativeElement.querySelector('.call-card button') as HTMLButtonElement).click();fixture.detectChanges();expect(accept).toHaveBeenCalledOnce();expect((fixture.nativeElement as HTMLElement).textContent).toContain('1m 5s');fixture.componentInstance['complete']();expect(complete).not.toHaveBeenCalled();expect(fixture.componentInstance['outcome'].touched).toBe(true);expect(fixture.componentInstance['outcome'].invalid).toBe(true);fixture.componentInstance['outcome'].setValue('Resolved');fixture.componentInstance['notes'].setValue('x'.repeat(2001));fixture.componentInstance['complete']();expect(complete).not.toHaveBeenCalled();fixture.componentInstance['notes'].setValue('Done');complete.mockReturnValue(of({...active,status:'Completed'}));fixture.componentInstance['complete']();expect(complete).toHaveBeenCalledOnce()});
 it('refreshes current call after a 409 accept conflict',()=>{accept.mockReturnValue(throwError(()=>({status:409,message:'Conflict',validationErrors:{},traceId:null})));
 (fixture.nativeElement.querySelector('.call-card button') as HTMLButtonElement).click();fixture.detectChanges();expect(current).toHaveBeenCalledTimes(2);expect((fixture.nativeElement as HTMLElement).textContent).toContain('Latest current call')});
 it('pauses hidden polling, resumes immediately, polls without overlap, and stops on destroy',async()=>{let hidden=true;const spy=vi.spyOn(document,'hidden','get').mockImplementation(()=>hidden);vi.useFakeTimers();document.dispatchEvent(new Event('visibilitychange'));const count=current.mock.calls.length;await vi.advanceTimersByTimeAsync(6000);expect(current).toHaveBeenCalledTimes(count);hidden=false;document.dispatchEvent(new Event('visibilitychange'));await vi.advanceTimersByTimeAsync(0);expect(current).toHaveBeenCalledTimes(count+1);await vi.advanceTimersByTimeAsync(3000);expect(current).toHaveBeenCalledTimes(count+2);fixture.destroy();await vi.advanceTimersByTimeAsync(3000);expect(current).toHaveBeenCalledTimes(count+2);spy.mockRestore();vi.useRealTimers()});
});
