import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { of, Subject, throwError } from 'rxjs';
import { AgentResponse } from '../../../core/api/models/agent.models';
import { AgentsApiService } from '../../../core/api/services/agents-api.service';
import { CallQueuesApiService } from '../../../core/api/services/call-queues-api.service';
import { SnackbarNotificationService } from '../../../shared/services/snackbar-notification.service';
import { AgentAdministration } from './agent-administration';

describe('AgentAdministration',()=>{
 const list=vi.fn(),create=vi.fn(),update=vi.fn(),assignToQueue=vi.fn(),show=vi.fn();let fixture:ComponentFixture<AgentAdministration>;
 const agent={id:'a1',displayName:'Agent One',status:'Available' as const,lastAvailableAtUtc:null,currentCallReference:null,callQueueNames:['Support']};
 const response:AgentResponse={id:'a1',displayName:'Agent One',status:'Available',lastAvailableAtUtc:null,callQueueNames:['Support']};
 beforeEach(async()=>{vi.clearAllMocks();list.mockReturnValue(of([agent]));await TestBed.configureTestingModule({imports:[AgentAdministration],providers:[provideNoopAnimations(),{provide:AgentsApiService,useValue:{list,create,update,assignToQueue}},{provide:CallQueuesApiService,useValue:{listActive:()=>of([{id:'q1',name:'Support',description:null,isActive:true}])}},{provide:SnackbarNotificationService,useValue:{show}}]}).compileComponents();fixture=TestBed.createComponent(AgentAdministration);fixture.detectChanges()});
 it('renders list and completes create, edit, and queue assignment flows',()=>{expect((fixture.nativeElement as HTMLElement).textContent).toContain('Agent One');const createResult=new Subject<AgentResponse>();create.mockReturnValue(createResult);fixture.componentInstance['createForm'].setValue({fullName:'Agent One',displayName:'Agent One',email:'agent@example.com',password:'Agent@123'});fixture.componentInstance['create']();fixture.componentInstance['create']();expect(create).toHaveBeenCalledOnce();createResult.next(response);createResult.complete();expect(list).toHaveBeenCalledTimes(2);fixture.componentInstance['choose'](agent);fixture.componentInstance['editForm'].setValue({displayName:'Agent Updated'});update.mockReturnValue(of({...response,displayName:'Agent Updated'}));fixture.componentInstance['update']();expect(update).toHaveBeenCalledWith('a1',{displayName:'Agent Updated'});expect(list).toHaveBeenCalledTimes(3);fixture.componentInstance['choose'](agent);fixture.componentInstance['assignmentForm'].controls.callQueueId.setValue('q1');assignToQueue.mockReturnValue(of(undefined));fixture.componentInstance['assign']();expect(assignToQueue).toHaveBeenCalledWith({agentId:'a1',callQueueId:'q1'});expect(show).toHaveBeenCalledWith('Queue assignment saved. Existing assignments remain unchanged.')});
 it('blocks invalid forms and preserves field-level server errors while clearing password',()=>{fixture.componentInstance['create']();expect(create).not.toHaveBeenCalled();expect(fixture.componentInstance['createForm'].controls.fullName.touched).toBe(true);fixture.componentInstance['createForm'].setValue({fullName:'Agent',displayName:'Agent',email:'agent@example.com',password:'Agent@123'});create.mockReturnValue(throwError(()=>({status:400,message:'Validation failed',validationErrors:{Email:['Email already exists.'],Password:['Password rejected.']},traceId:null})));fixture.componentInstance['create']();expect(fixture.componentInstance['createForm'].controls.password.value).toBe('');expect(fixture.componentInstance['createForm'].controls.email.getError('server')).toEqual(['Email already exists.']);expect(fixture.componentInstance['createForm'].controls.password.getError('server')).toEqual(['Password rejected.']);expect(fixture.componentInstance['formError']()).toBe('Validation failed')});
});
